systemjs/systemjs

- lib/extension-amd.js
- test/test.js
- test/tests/amd-require.js
> Allow amd-style requires with no callback

- README.md
> Fix paths documentation URL.

- package.json
Looks like this got overlooked
> Correct test:babel in package.json

- lib/extension-es6.js
- lib/polyfill-wrapper-end.js
+ allow to dynamically load transpiler
> improve WebWorker support

- README.md
I've created a plugin that handles Handlebars (not Ember Handlebars)
> add Handlebars plugin

- docs/config-api.md
as discussed in #501. If there are other examples of what map can do that paths can't, I can add them.
> Update map/paths docs

- README.md
Raw plugin allows loading files as ArrayBuffers.
> Add raw plugin to list of plugins.

- bower.json
Add not distributable files to bower ignore.
> [bower] Don't distribute dev files

- docs/config-api.md
> Added link to module formats page

- bower.json
> Fix the bower package name.

- docs/config-api.md
See: https://github.com/systemjs/systemjs/issues/664
> Clarifing meta and packages path normalization

- README.md
I think others might find this a useful plugin and I've finally managed to get the bugs out of it.
> Add Jade VirtualDOM to list of additional plugins

- README.md
> Added information about node runtime loading using jspm for config

- lib/cjs.js
- test/test.js
- test/tests/commonjs-d2.js
- test/tests/commonjs-requires.js
This is a reworking of https://github.com/systemjs/systemjs/pull/336 with some other ideas.
Instead of removing the strings and comments, we simply track their locations then check against these indices sensibly when doing the require detection to rule-out false positives.
//cc @theefer would value your eye on this one if you can still remember the problem space :)
> Strings v2

- lib/package.js
Fixes https://github.com/jspm/jspm-cli/issues/1341.
> Allow global meta to provide opt-out of package extension adding

- docs/config-api.md
Remove the c from 'w3c.org' to resolve nonce url properly
> Fix broken url

- README.md
> readme: link to HTML Imports loader

- README.md
Hi @guybedford, 
we have added the support for projects to Supporter and I have created a new badge for SystemJS as well. Also I have submitted a PR to jspm https://github.com/jspm/jspm-cli/pull/1540
I would love to hear you feedback.
Thanks!
> New Support SystemJS badge

- docs/config-api.md
Attempt to clarify value of `scriptLoad` meta docs.
> Clarify scriptLoad

- lib/core.js
> Make the location of the system.js script accessible

- README.md
I found my self slightly confused while reading one portion of the `README.md`.  I propose the following update to wording in order to eliminate this moment of confusion for any future readers of the read me |:^).
> Make the README.md more understandable

- src/instantiate.js
- test/test.js
- test/tests/amd-bundle.js
If bundle has some wildcard convert the wildcard-bundle to a regexp and check if it's match.
Closes #1089
> wildcard in bundles include the / boundaries

- docs/system-api.md
Feel free to add anything to clarify. 🌷
> Add doc for resolveSync()

- docs/module-formats.md
> Typo in module-formats.md

- docs/module-formats.md
<del>fixes #1666</del>
Edit: Well, partially. The other part is explaining [how to configure it](https://github.com/systemjs/plugin-json/pull/19).
Now having figured it out, it works perfectly. Thanks a lot! :+1:
> docs/module-formats: hint at plugins

- src/instantiate.js
- test/test.js
- test/tests/x-error.js
Resolves https://github.com/systemjs/systemjs/issues/1664
> Make sure the source-maps represent the locate plugin address

- package.json
- src/features/basic-resolve.js
- test/system-core.js
> Changing basic resolve to return Promise. Resolves #1909.

- docs/import-maps.md
> Fixed typo

- docs/api.md
- src/features/registry.js
- test/system-core.js
Example usage:
```js
for (let entry of System) {
console.log(entry) // ['http://hi', {firstExport: 'value'}]
}
```
> Making the registry iterable. See #1918.

- src/features/import-map.js
> Supporting late import maps. Resolves #1916.

- README.md
See https://github.com/webpack/webpack/releases/tag/v4.30.0
> Updating webpack documentation

- src/features/script-load.js
Reverts systemjs/systemjs#1950
> Revert "Implementing loading JSON modules. Resolves #1949."

- src/features/script-load.js
See #1962. This is a regression from #1959.
> Using substr instead of endsWith. Resolves #1962.

- src/features/script-load.js
- test/browser/core.js
> Reserve html modules for future implementation. See #1992.

- src/features/script-load.js
This also improves the compressed output size.
> Replace usage of substr with slice

- README.md
See https://github.com/joeldenning/systemjs-webpack-interop
> Adding link to systemjs-webpack-interop

- src/system-core.js
https://github.com/systemjs/systemjs/commit/13821448933269533e6cf524d0b6cf16584a9a7d introduced the console.log into 6.1.3
> Removing unneeded console.log

- README.md
As discussed in https://github.com/systemjs/systemjs/issues/2040.
> Update examples to use System.import

- src/extras/module-types.js
- test/browser/core.js
- test/fixtures/css-modules/hash.css
- test/fixtures/css-modules/search-param.css
- test/system-core.js
Fixes https://github.com/systemjs/systemjs/issues/2087
> fix: strip search param and hash when determining module type

- README.md
- package.json
This updates the readme and project with the Open Collective sponsorship info.
> Activate Open Collective

- docs/api.md
See related https://github.com/systemjs/systemjs/issues/2100 and https://github.com/systemjs/systemjs/issues/2062 where this was discussed.
@newmanw @guybedford
> Improving docs for System.set

- src/extras/amd.js
- test/browser/named-register.js
- test/fixtures/browser/amd-named-single-execute.js
See #2103.
@guybedford I'd appreciate your thoughts on this.
> Fixing bug - named AMD modules were instantiated twice. Resolves #2103.

- src/extras/named-register.js
- test/browser/named-register.js
- test/fixtures/browser/importmap.json
- test/fixtures/browser/named-register-single-execute-as-dep.js
- test/fixtures/browser/named-register-single-execute.js
Resolves #2107. Note that this behavior could potentially impact some code that is relying on (what I consider to be broken) behavior in systemjs@6.1.9.
> Prefer import map resolution over registerRegistry. Resolves #2107.

- src/extras/amd.js
- test/browser/named-register.js
> Supporting multiple define variations for named modules. Resolves #2118.

- README.md
This is one of the more common questions I hear about how to use SystemJS.
> Adding documentation for using npm packages

- docs/import-maps.md
> Adding note about multiple import maps support. Resolves #2095.

- README.md
Some minor Readme updates to try and put the loader into as much context as possible.
> Notes on Node.js loader usage

- docs/errors.md
See related https://github.com/systemjs/systemjs/blob/953b0581969ddb37ad0e798c512a16ed2721563f/src/extras/module-types.js#L29 and https://github.com/systemjs/systemjs/issues/2176
> Update error code 4 content-types docs

- docs/errors.md
This PR addresses https://github.com/systemjs/systemjs/pull/2177#discussion_r409027711
> Updating error code docs

- README.md
I think it's important to keep pushing the performance benefits of SystemJS!
> Performance notes in readme

- src/common.js
- src/features/script-load.js
Fixes #2220 by restricting setting the cross origin attribute only on actual cross origin requests.
/cc @LarsDenBakker let me know if this works for you.
> Safari cross origin fix

- .github/ISSUE_TEMPLATE/question.md
Just updating to reflect the latest changes to systemjs.
> Add system-node.cjs to issue template

- README.md
- src/features/script-load.js
Seems this IE11 bug crept in on a recent PR of mine.
> Fix startsWith for ie11

- src/features/import-maps.js
- test/test.html
Implements https://github.com/systemjs/systemjs/issues/2254.
> Implement import map integrity

- src/extras/module-types.js
Fixup handling of bad responses and a log that crept in.
> Fixup response handling, invalid log

- README.md
- docs/hooks.md
This includes a number of readme updates - updating the feature list of the builds to the latest state, while also cutting back on the content and including the key features as the first thing in the readme.
/cc @joeldenning for further review before release here.
> Readme updates

- src/features/script-load.js
I just discovered another case where Brave inserts a dapp script which interferes with the auto import detection.
Hopefully we don't discover too many more of these!...
> Fix another auto import race

- test/server.cjs
This will help avoid any issues during testing...
> Disable caching for test server

- .github/workflows/size-impact.yml
Fixes up the remaining CI issues.
> ci: fixup size impact script

- chompfile.toml
@guybedford 
Just a simple fix for the test cases.
> test: fix typo in chompfile.toml

- src/system-core.js
Fixes the regression in https://github.com/systemjs/systemjs/pull/2404 as pointed out in https://github.com/systemjs/systemjs/commit/01bac3ec5270006720ed3bd655c891aa87a84cd3#r82284793.
> fix: const declaration

- src/extras/module-types.js
- test/system-node.mjs
> avoid module-types override shouldFetch

- docs/system-register.md
https://github.com/systemjs/systemjs/issues/2432
> add import assertions to system-register.md
