test/test.js, test/tests/connected-tree/a.js, test/tests/connected-tree/b.js, test/tests/connected-tree/c.js
Background of the problem: https://groups.google.com/forum/#!topic/systemjs/ecPVGbX0MVQ
I have something like the following: 
```js
// a.js 
require('./b'); 
require('./c'); 
// b.js 
import from "./c" 
// c.js 
require('d'); 
```
And this breaks.
=> Adds tests showing a problem with connected trees and es modules in the middle

lib/extension-cjs.js, test/test.js, test/tests/commonjs-requires.js
Fixes https://github.com/systemjs/systemjs/issues/311
Bit of a tedious job as I couldn't find an elegant way to update `cjsRequireRegEx` to check whether/reject if the match is within a string. The solution I arrived to is to strip all strings from the source if they are not prefixed by (`require(`). In the absence of lookbehind in JS regex, I have to fallback to an explicit prefix check in the replace function.
I've not restricted this to non-minimised files, since I expect the issue would arise even in minimised files.
The only minor worry is whether this operation is too expensive, but hard to judge without a bit of a performance testing harness.
=> Avoid parsing require("dep") inside strings in CJS

test/test.js, test/tests/shared-dep-bundles/a.js, test/tests/shared-dep-bundles/b.js
A test that currently breaks - given two bundles `a.js` and `b.js` with a shared dependency, System.import() currently fails depending on the order in which the bundles are imported.
=> Test for shared dependency bundle bug

lib/extension-plugins.js
If a module is configured with path not ending in '.js', the old behaviour will incorrectly remove the last 3 chars from the address.
=> Fix plugin extension returning wrong address when .locate()

README.md
Add a link to a wiki page that comprises all configuration options.
=> comprise configuration options

README.md
Added the plugin which we use to compile Ember Handlebars templates. It works with Ember 1.10+ and uses ember-template-compiler to actually compile templates.
=> Added Ember Handlebars plugin

docs/config-api.md
A couple of options seem to have got left behind, so this PR brings them all to the System.config() function. Hope I've got these right :-)
I was going to do the same on es6-module-loader, but then I noticed that config() isn't in there, but in systemjs. A bit inconsistent (but hardly a major issue)
=> Update docs/config-api to config()

docs/config-api.md
a curious feature (or maybe bug) of GFM I never noticed before - it auto-creates links, but converts camel-case to lower-case. With this change all the links in this file should now work :-)
If I spot any others that don't work, I'll change them too.
=> config-api.md GFM internal links are lower-case

lib/core.js, lib/package.js, lib/paths.js, test/test-jsextensions.html, test/test.js, test/tests/testpkg/test.ts, test/tests/typescript.ts
Two features which are breaking against 0.17, but which may be useful API adjustments at this point:
1. TypeScript users need to use custom extensions with `defaultJSExtensions` compatibility mode. We enable this by making js extensions behave after paths instead of before, and if a path changes the file extension, we don't add the js extension. See https://github.com/systemjs/systemjs/issues/506 for more info.
2. A smaller one, but also breaking - package map config maps two types of requires - paths within the package and also requires within the package. These are really two separate concerns, which is made clearer by calling these paths and map which is more in line with the terminology. This also allows more flexibility against some edge cases that might have caused issues. See …
=> Pathing adjustments - possible 0.18

docs/module-formats.md
Github's auto-links are lower-case
=> module-formats.md fix intra-page links

lib/register.js
I made this change in an effort to get Express working. I also had to change "negotiator" under "npm:accepts@1.1.4" in my config.js. It was at version 0.4.9 and I bumped it up to 0.5.0. That got everything working with jspm run.
edit: sorry for the multiple commits. I had to (improperly) re-make these changes in github's editor.
=> prevented execution of module getters on import

bower.json
Add missing main property, it allows automation using main-bower-files tool.
```json
{
"name": "systemjs",
"main": "./dist/system.js",
"devDependencies": {
"qunit": "~1.12.0"
}
}
```
=> Add main property in bower.json

lib/alias.js
Currently, if you define an alias to on an entry and add dependencies for the alias the aliased entry gets loaded before its dependencies.
```javascript
System.config({
"meta": {
"a": {
"alias": "b/submodule",
"format": "global",
"exports": "b",
"deps": [
"b/submodule-dependency"
]
}
}
```
In the above case `b/submodule` would be loaded before `b/submodule-dependency`.
=> Fix load order for dependencies of aliased entries

lib/proto.js, lib/register.js, test/test.js, test/tests/duplicateDeps/m1.js, test/tests/duplicateDeps/m2.js
currently if dependency list contains multiple duplicate entries - setter is called only for the first one. This PR fixed this by capturing indices of duplicated from the original dependency list and using them to invoke setters
=> correctly handle duplicate entries in dependency list

lib/core.js, lib/plugins.js, test/test.js
The ```pluginFirst``` is a boolean property of loader similar to defaultJSExensions. Setting it to true causes SystemJS to follow the plugin syntax of AMD and webpack, where the plugin name comes before the resource identifier. Old syntax was ```[resource ID]![plugin module ID]```. With pluginFirst turned on, ```[plugin module ID]![resource ID]```. See [https://github.com/amdjs/amdjs-api/blob/master/LoaderPlugins.md](https://github.com/amdjs/amdjs-api/blob/master/LoaderPlugins.md) for exact details. Should resolve issue #549.
so ```System.import('./index.coffee!coffee')```
becomes ```System.import('coffee!./index.coffee")```
Note that the old anonymous plugin support like ```System.import("file.coffee!")``` which is short for ```System.import("file.coffee!coffee")``` is not enabled. …
=> Loader first global

lib/global-eval.js
I have an application with a `window.onerror` defined, and it seems that SystemJS is overriding it so that the custom function is not called. This updates SystemJS so that it invokes the existing `window.onerror`
=> Allow for custom error handling.

docs/config-api.md
Clarifying that meta paths are subpaths within package paths.
See: https://github.com/systemjs/systemjs/issues/692
=> Docs: packages meta path

docs/config-api.md, lib/global-eval.js, lib/scriptLoader.js, test/test-csp-inline.html, test/test-csp.html, test/test.js, test/tests/csp/integrity.js, test/tests/csp/nonce.js, test/tests/csp/nonce2.js
The script loader will use load metadata to set script properties. This allows what is in the script tag to be set in meta.
There are two primary use cases: CSP nonce and subresource integrity.
Users of SystemJS wanting to take advantage of CSP can set a "nonce" value in their CSP config. Setting the meta attribute "nonce" for plugins and formats that cannot use CSP allows safely bypassing CSP. Note that this will only work in places where "document" is available. See the test-csp-inline.html file for a full example.
In addition, subresource checking mentions in #639 is also implemented. In the same way setting "integrity" in the meta should make this possible. See test-csp.html for a full example.
=> Enable setting properties on script element.

lib/core.js, lib/package.js, test/test.js, test/tests/testpkg.json
This implements a `packagePaths` scheme, which when matched will load a `.json` configuration file to configure the package before proceeding with the package request. This allows packages to be loaded dynamically, without their configuration needing to be present in the SystemJS config file already.
=> Dynamic configuration requests for packages

Makefile, index.js, test/test-csp.html, test/test-register-only.html, test/test.js
This would probably be useful to have...
`System.version` version strings output are:
* `"0.18.17 Standard"` - for the normal system.js build
* `"0.18.17 CSP"` - for the system-csp build
* `"0.18.17 Register Only"` for the register-only build
* `"0.18.17 Node"` - when running in NodeJS
=> Implement System.version

lib/alias.js, test/test.js, test/tests/package-local-alias/index-cjs.js, test/tests/package-local-alias/index-default-cjs.js, test/tests/package-local-alias/index-default-esm.js, test/tests/package-local-alias/index-esm.js, test/tests/package-local-alias/local/index-cjs.js, test/tests/package-local-alias/local/index-default-cjs.js, test/tests/package-local-alias/local/index-default-esm.js, test/tests/package-local-alias/local/index-esm.js
This fixes a bug I encountered while trying to use meta : {alias : ... } in package config - groupIndex was left uninitialized in the entry created in alias.js, which in my case lead to buildGroups producing groups 'array' with two indices: 0 and NaN
=> Fix for alias meta in package config

README.md
It was difficult to see that "Creating plugins" was a separate hyperlink because it was adjacent to "Using plugins." I've moved them to separate lines.
=> Indent hyperlinks

README.md
I had the use case of creating a lazy version of [plugin-image](https://github.com/systemjs/plugin-image) to improve the page load time of a page with a carousel. Using SystemJS plugins is nice as it ties the code implementing the behavior, here the carousel, with the assets needed (the images and/or the css). However, plugin-image was blocking the carousel code to be executed until all the images were fully loaded. Using `System.import`s instead of `import`s would have only solved half of the issue, since it returns only when the images are fully loaded (no progressive rendering), and the module's dependencies can't be statically traced anymore (which I use to detect unused files). Please advice if there's a better approach.
=> Add plugin-lazyimage to README

docs/config-api.md, lib/scriptLoader.js
We're hosting our static files on a CDN, so we're often faced with limitations of [Same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). One of such limitations is that scripts loaded from a different domain don't provide [extended error information](https://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onerror#Notes) when an exception is thrown. All you get is `"Script error."` message and nothing else.
When combined with `scriptLoad`, the `crossOrigin` option allows to set [additional property](https://developer.mozilla.org/en/docs/Web/API/HTMLScriptElement#crossOrigin_property) on the script element to allow rich error reporting for scripts loaded from a different origin.
```js
meta: {
"*.js": {
format: "register",
scriptLoad: true, …
```
=> added `crossOrigin` meta option

lib/global-eval.js
We don't add new line in the beginning of the file to avoid one line offset issue. So we must not change existing source mappings.
See https://github.com/frankwallis/plugin-typescript/issues/110#issuecomment-201242615
=> Fix "Source Maps are off"

lib/package.js
I was experimenting with lodash-es in jspm 0.17 and getting 404 errors on:
```
http://localhost:8080/jspm_packages/npm/lodash-es@4.6.1/valueOf
http://localhost:8080/jspm_packages/npm/lodash-es@4.6.1/toString
```
with:
```
"jspm": {
"dependencies": {
"lodash-es": "npm:lodash-es@^4.6.1"
},
"overrides": {
"npm:lodash-es@4.6.1": {
"format": "esm",
"defaultExtension": "js"
}
}
}
```
This was really strange because the dozens of other subPaths coming in from lodash were resolved to the actual `.js` file fine.  I did some stepping and found:
```
var exactMeta = pkgMeta[subPath] || pkgMeta['./' + subPath];
```
Which is going to work for *most* cases, but not for prototypal properties `toString` and `valueOf`.
=> getMetaMatches should check for own property

lib/proto.js
See #1192 for an explanation of the bug this fixes. My solution is to be defensive when calling `Object.getOwnPropertyDescriptor`, falling back to just setting the property normally when `getOwnPropertyDescriptor` throws (even though a `setter` is potentially being fired). I didn't dive deep enough into the code to find out how hard it would be to write a test for this use case, but I did test this locally and saw that my app, that was unable to bootstrap in IE11 without this code, is now able to properly bootstrap. Let me know if there's a good way to write a test for it though.
Also, assuming that this is merged, when could I hope for it to be published to npm? The company I work for is hoping to launch a new product in about next two weeks, and I'd rather not have to deploy my fork of …
=> Fixing #1192. Falling back to normal way of setting properties when getOwnPropertyDescriptor throws

README.md
Just putting this out there, an alternative sass/scss plugin, born from needing to capture the CSS output and inject where you want, not the 'head', e.g. Angular 2's @Component style attribute.
=> Update to add alternative sass/scss plugin

package.json
The npm package includes a whole bunch of things that seem not to be used for neither browser usage or node usage. Mainly `test` and `lib` seem to be unneeded in the distributed package, and of course all the project files.
This PR adds a white listed array of files to include in the npm package.
Before:
```
systemjs-0.19.26.tgz
package/package.json
package/.npmignore
package/README.md
package/LICENSE
package/index.js
package/bower.json
package/.agignore
package/dist/system-csp-production.js
package/dist/system-csp-production.src.js
package/dist/system-polyfills.js
package/dist/system.js
package/dist/system-polyfills.src.js
package/dist/system-register-only.src.js
package/dist/system.src.js
package/dist/system-register-only.js
package/dist/system-register-only.js.map …
```
=> Only include actively used files in npm package

lib/conditionals.js
I think there is a copy paste error in naming. 
I wish there would be a SystemJS without all this „hook“ magic. Makes code pretty hard to understand.
=> Fixed wrongly named parameter... seems to be copy paste error from "import".

docs/creating-plugins.md
The default fetch function is passed as the second argument, not as the third one.
=> Fix error in documentation of plugin fetch hook

src/system-production.js
The SystemJS.register requires the correct `this`. If modules are registered using `System.register` (as opposed to `SystemJS.register`) AND there exists another `global.System` object, the register module call fails, in my case the error was: 
```
register-loader.js:456 Uncaught TypeError: Cannot set property 'lastRegister' of undefined
at Object.RegisterLoader$1.register (register-loader.js:456)
at Object.systemJSPrototype.register (systemjs-production-loader.js:206)
at Object.envGlobal.System.register (system-production.js:22)
at main.js:1
```
=> Fix the context scope of SystemJS.register when called from browsers System.register

docs/config-api.md
quick fix to match the casing of pluginFirst link to the heading
=> Fix broken in-page link to pluginFirst section

src/resolve.js
As [mentioned in issue 1658](https://github.com/systemjs/systemjs/issues/1658#issuecomment-320234623), this is an extra fix earlier in the process of package resolving, in the case of plugin-hbs for resolving a child package within a parent.
=> fix for issue #1658 when no package meta is present.

src/instantiate.js
I dove into SystemJS plugin writing and instantly found I could not get a module transpiled if I did not implement the 'translate' method.
script.js:
```javascript
#!/usr/bin/env node
const SystemJS = require('systemjs')
SystemJS.config({
map: {
'plugin-babel': 'node_modules/systemjs-plugin-babel/plugin-babel.js',
'systemjs-babel-build': 'node_modules/systemjs-plugin-babel/systemjs-babel-node.js'
},
meta: {
'builtin/*': {
loader: 'builtin-loader.js',
}
},
transpiler: 'plugin-babel',
})
const main = async () => {
const realmod = await SystemJS.import('./real-module.js')
console.log('=> real-module:', realmod)
const builtinmod = await SystemJS.import('builtin/helloworld')
console.log('=> builtin:', builtinmod)
}
main()
```
real-module.js:
```javascript
const x = () => "hi" ; export {x as …
```
=> fix plugin without translate still transpiling

src/common.js
using a module with require(\`foo\`) fails to be detected as a common js module.
=> Support backticks (`) in cjs require module detection

src/fetch.js
This allows http(s) requests from NodeJS.
```javascript
// set global fetch (not the same as self.fetch)
global.fetch = require('node-fetch');
// this will use nodeFetch by default
const SystemJS = require('systemjs');
// nodeFetch will fail regex on `file://` prefix and fallback to fetchFetch logic
SystemJS.import('https://unpkg.com/react@16.0.0/umd/react.production.min.js').then(react => {
console.log('react', react);
});
```
related topic: https://github.com/systemjs/systemjs/issues/1543
=> Enable nodeFetch to fallback to fetchFetch

src/extras/global.js
Safari does this strange thing where new globals added to Window sometimes show up at `Object.keys(window)[0]` and `Object.keys(window)[1]`. So far these are the only variations I've detected so I've simply added this in to the detection. Ahh browsers.
=> Fix global detection in safari

docs/api.md, src/features/registry.js, test/system-core.js
This adds support for `System.has` and `System.set` for the SystemJS API (not the s.js API).
May help provide a path for use cases like #1869.
=> Support System.has and System.set

docs/api.md
System.has docs shows the incorrect call, probably copied over from System.get
=> system.has docs update

src/common.js, src/features/import-map.js, test/import-map.js
See related #1860. cc @blittle @guybedford @frehner. This implements import map merging from the specification for import maps. I have verified that it's generally working, although I wanted to get some initial feedback before spending the time to write extensive tests.
See related [import maps proto spec](https://github.com/WICG/import-maps/blob/master/spec.md#merging-import-maps) and [import maps readme](https://github.com/WICG/import-maps#import-map-processing) for where I got the information on how the spec should work.
=> Implementing support for multiple import maps.

docs/api.md
Removed unneeded parentheses from ```System.entries``` example, in order to work as expected.
=> Remove unneeded parentheses

src/features/registry.js
Computed object properties are not supported in IE11. See #1935
=> Fixing IE11 compatibility for System.entries(). Resolves #1935.

src/common.js, src/extras/amd.js, src/extras/transform.js, src/features/basic-resolve.js, src/features/script-load.js, src/features/wasm-load.js, src/system-core.js
You can call `Error()` without using `new` and it behaves exactly the same as if you had done `new Error()`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Used_as_a_function. I have done this for a year or two now, including when supporting IE11. So I think this should work in all of systemjs' browsers.
Switching from `new Error()` to `Error()` saves 32 bytes in the dist files, between system.min.js and all of the extras.
=> Switching from new Error() -> Error() to save bytes.

src/features/script-load.js
Resolves #1949 
Checking `url.endsWith('.json')` is incomplete and not spec compliant. But it's an easy implementation that does not require first trying `<script>` tag and then trying XHR + `JSON.parse()` if the script fails.
Open to any feedback on that decision.
=> Implementing loading JSON modules. Resolves #1949.

src/extras/amd.js, src/extras/global.js, src/extras/named-exports.js, test/browser/amd.js, test/browser/named-register.js, test/fixtures/browser/amd-module-esm-dep.js, test/fixtures/browser/esm.js
This resolves https://github.com/systemjs/systemjs/issues/1933 while ensuring that we don't break the standard interop patterns.
=> Support amd importing esm through __useDefault pattern

src/features/script-load.js
See #1960. Also see https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent#Browser_compatibility. The `errEvt.filename` property is supported in all evergreen browsers, but IE11 support is unknown.
The fix is to only reject the System.import() promise if the error reported to the window event listener originated from the script at the URL for the one specific module that is being imported.
=> Fix for System.import() rejecting for other script's errors. Resolves #1960

src/features/script-load.js
See #1965. I believe that the error described in the issue only occurs in strict mode, which is what explains why it wasn't caught by our testing.
=> Fix ReferenceError. Resolves #1965.

src/extras/named-exports.js, test/browser/named-exports.js
Resolves #1977 in ensuring the named exports extra correctly applies to AMD modules defined using the `"exports"` assignment approach.
=> Fixup named exports extra for amd exports

src/common.js, test/import-map.js
This implements https://github.com/systemjs/systemjs/issues/1968 in resolving scopes relative to the baseUrl, as was implemented in the import maps spec update.
As a major change this will form a SystemJS v5, so it's worth thinking about if we have any other major changes we'd like to add to the mix before merging and releasing here.
=> Resolve scopes relative to import map base

src/extras/named-exports.js
See [this codepen](https://codepen.io/joeldenning/project/editor/ABpkMK#) for the weird behavior that this fixes.
The named-exports extra is accidentally changing the default export, if the exported object has a default property on it.
=> Fixing named-exports to not alter default export.

README.md
This updates the README to include a new Community Projects section, showcasing projects that build on top of SystemJS.
For now I've just got jspm, single-spa and js-env.
@dmail @joeldenning please see the copy included and project any updates to the text as necessary. I will wait for your confirmation before merging.
=> New community projects section

src/extras/amd.js, src/extras/global.js, src/extras/named-exports.js, src/extras/named-register.js, test/browser/named-register.js, test/fixtures/browser/importmap.json, test/fixtures/browser/named-bundle.js, test/fixtures/browser/single-named-module.js
See [this codepen](https://codepen.io/joeldenning/project/editor/ABpkMK#) for the weird behavior that this fixes.
Also see #1980 where people are doing a double System.import() to work around the current odd behavior.
=> Supporting System.import for a single named System.register module

docs/hooks.md, src/common.js, src/features/import-map.js, src/system-core.js, test/import-map.js
=> Changing System.resolve to be synchronous. Resolves #1985.

docs/hooks.md, src/system-core.js, test/system-core.js
As brought up in https://github.com/systemjs/systemjs/issues/1971#issuecomment-524636775, practical usage of `onload` tracing requires the dependencies to be returned.
This updates the tracing API to:
```js
System.onload(err, id, deps)
```
This is a major change due to swapping the err argument order so will go along nicely with v6 as well.
=> Add deps argument to onload hook

docs/module-types.md
This provides some minor updates to these docs - 
* Made the table a generic module type table including all supported module types as well as Web Assembly.
* Removed the ESM item in the table, as I would prefer not to indicate that the transform loader is a recommended way to load ESM
* Updated the polyfill snippet based on testing to one that can work reliably
* Minor edits
=> Update module type docs

docs/module-types.md
This moves the table right up to the top with the file extensions included in the table, with some updates to the file extension notes too.
=> Include file extensions in the table

docs/hooks.md, docs/import-maps.md, minify-extras.sh, src/common.js, src/features/import-map.js, test/fixtures/browser/importmap.json, test/fixtures/browser/named-amd.js, test/import-map.js
This implements https://github.com/systemjs/systemjs/issues/1999 for cascading import maps resolution, with the implementation behaviours as described in https://github.com/systemjs/systemjs/issues/1999#issuecomment-525359382.
In addition this fixes https://github.com/systemjs/systemjs/issues/2007 that scopes must end in a trailing slash.
The breaking changes are effectively:
1. Scopes must end in a trailing slash.
2. Bare specifiers on the RHS of an import map are no longer supported unless in a cascade.
=> Cascading import maps implementation

README.md, src/common.js, src/features/script-load.js, test/browser/core.js, test/fixtures/browser/systemjs-module-script.js, test/fixtures/browser/systemjs-module-script2.js, test/test.html
=> Loading type=systemjs-module scripts. Resolves #2002.

src/extras/module-types.js
See #2027. Note that the module-types extra has an `import` in it when it shouldn't.
https://github.com/systemjs/systemjs/blob/c08c92dcdb0850b999b6cf4c180702e01ae8b04d/dist/extras/module-types.js#L5
=> Removing import statement from module-types extra. Resolves #2027.

src/system.js, test/browser/core.js, test/fixtures/browser/systemjs-module-early.js, test/test.html
See #2024 
The root cause of the bug was order of execution. In 6.1.0, [Line 531](https://github.com/systemjs/systemjs/blob/c08c92dcdb0850b999b6cf4c180702e01ae8b04d/dist/system.js#L531) needs to execute *after* [line 760](https://github.com/systemjs/systemjs/blob/c08c92dcdb0850b999b6cf4c180702e01ae8b04d/dist/system.js#L760). So that `prepareImport` is patched before the first `System.import()` occurs. The bug was to rearrange the order of execution.
I reviewed all the features that import-map.js used to execute after but now is executing before. And none of them patch `System.resolve` or `System.prepareImport`, so I don't think there will be any side effects of changing up the order of execution.
=> Patching prepareImport before loading script modules. Resolves #2024.

src/extras/amd.js, test/browser/amd.js, test/fixtures/browser/amd-named-simple.js
Resolves #2026 
If an inline script calls `define('name', ...)` and then the next `System.import()` calls `define('other-name', ...)`, SystemJS currently accidentally counts the first call to `define()` to be the export for the System.import(), even though it's not even in the same file. This behavior is related to the desired behavior of having SystemJS use the first named register be the register for the overall module.
To solve this, I'm resetting things at the beginning of each System.import() so that inline scripts calling System.register or define won't interfere with loading a module with System.import().
Note that the newly added test fails without the changes to the amd extra, so it's a good reproduction case.
=> Fixing bug with AMD extra. Resolves #2026.

src/features/script-load.js
Replace `document.querySelectorAll(...).forEach` with `Array.prototype.forEach.call(document.querySelectorAll, ...)` due to old browsers (ex: IE 11) not supporting [`entries|forEach|keys|values`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Browser_compatibility) methods in NodeList.
=> Fix old browsers not supporting `forEach` in `querySelectorAll` result

src/common.js, test/import-map.js
Resolves #2038 in resolving the LHS in maps (when not a bare specifier) relative to the baseURL.
This baseURL LHS normalization is used to resolve both imports and in scopes, as per the spec.
=> Handle resolution of relative URLs LHS in import maps

src/extras/named-register.js
Another potential fix for #2040. This directly addresses the problem that causes the bug in #2040, but doesn't address the deeper underlying issues related to `System.import()` being called before all the extras are loaded.
=> Fix for named-register extra. Resolves #2040.

src/extras/amd.js, src/extras/global.js, src/extras/module-types.js, src/extras/named-exports.js, src/extras/named-register.js, src/extras/transform.js, src/extras/use-default.js
Hi,
Is it ok for the "extras" to access `System` from the "global" passed in, instead of the `System` found in the current execution context? Seem the correct thing to me, if you don't care.
I just changed the ` src/extras/*` files, but something seens that was not built in the last commit https://github.com/systemjs/systemjs/compare/master...esroyo:master#diff-5d8dcd1a2a96334214577c42caccb58f
Thanks so much
=> Access the `System` variable through `global` in Extras

README.md
This removes mention of the use-default extension from the docs, in line with concerns in https://github.com/systemjs/systemjs/issues/2045.
Full deprecation can then happen in a subsequent major but there is no rush.
=> Docs deprecate use-default

src/features/registry.js, src/system-core.js
With this API the registry delete function will return an update function that can be called later on once the module is reimported.
When that happens, any modules that previously depended on the deleted module will get rebound to the new module, effectively using ES module live bindings to do this.
The `has` API function is also updated to return true on in-progress loads.
Will be useful for fully-live hot reloading workflows, as in https://github.com/systemjs/systemjs/pull/2014.
=> Support registry delete returning update function

src/extras/amd.js, test/browser/named-register.js
Resolves #2073. I verified that this adds 49 bytes to the amd.min.js extra.
=> Fixing bug where named-exports didn't work on named registers. Resolves #2073.

src/system-core.js, test/browser/core.js, test/fixtures/browser/__esModule.js
Resolves #2090. Webpack sets the __esModule property as [not enumerable](https://github.com/csr632/systemjs-issue-2090/blob/72132d1d04241871de00476a977ba6eacb6b7b87/dist/math-add.js#L54) (note that when you don't define enumerability that it defaults to false). Since it's not enumerable, it doesn't end up on the systemjs `ns` object. This is problematic because that flag is needed when webpack bundles interop with each other.
=> Ensure that __esModule is copied to ns even if it isn't enumerable.

docs/hooks.md
See https://github.com/systemjs/systemjs/issues/2092#issuecomment-573173092 which made me realize that instantiate is not currently documented.
=> Add documentation for instantiate hook

src/extras/named-register.js
Zero milliseconds is the default. https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout
=> Omit setTimeout milliseconds (saves bytes).

README.md
I've had a couple people tell me that they found this video useful, so I thought I'd propose it as part of the Readme. Would not be offended if there are reasons not to merge this.
@guybedford thoughts?
=> Add link to introduction video

src/extras/amd.js, src/extras/named-register.js
See #2111. Also see https://github.com/systemjs/systemjs/pull/2105#discussion_r367777343, where our `setTimeout`'s were listed as an item we needed to address.
The bug in #2111 related to race conditions of clearing out the `firstNamedDefine` due to our usage of setTimeout. We really just want it to clear out once the named define has been used once, which is what this pull request changes about the amd and named-register extras.
=> Fixing race conditions with named register modules. Resolves #2111.

src/extras/amd.js, src/extras/named-register.js, test/browser/named-register.js, test/fixtures/browser/amd-named-thing-as-dep.js
See #2115. This was caused by removing the setTimeouts in https://github.com/systemjs/systemjs/pull/2114. We are now resetting the firstNamedDefine in two situations:
1) getRegister is called
2) System.import() is called.
=> Fix problem with named register modules. Resolves #2115.

src/extras/amd.js, src/extras/named-register.js, test/browser/named-register.js, test/fixtures/browser/anonymous-define.js, test/fixtures/browser/anonymous-register.js, test/server.js
Unfortunately, @frehner and @TheMcMurder found some more race conditions that I overlooked in #2116.
Without the setTimeout, unexpected named calls to `define()` or `System.register()` while waiting for a `System.import()` to finish results in the wrong module being returned from getRegister(). If the calls to `define()` are a result of a `System.import()`, there is no problem. However, if the calls are not because of a `System.import()`, there is a problem.
I'm surprised I didn't think of this fairly obvious use case, and also that our tests didn't catch it. I've added two more tests that catch it now. All previous tests continue to pass with this change.
=> Fixing more named register race conditions.

package.json, test/server.cjs
This is handy for when you can't debug the test in 10 seconds, which usually causes the server to shut down. Also, renaming the file to `.cjs` fixed a warning - systemjs has `type` set to module so it has to use `.cjs` to load up commonjs modules
=> Adding test-browser-watch script, and fixing nodejs cjs/esm interop warning

src/extras/amd.js, src/extras/named-register.js
See related https://github.com/systemjs/systemjs/issues/2139 and #2138. Note that this is an alternative implementation to #2140 -- this one preserves the `firstNamedDefine` behavior.
@freezesoul @shrinktofit can you confirm is this fixes the problems that you reported? If not, I think we'll go with #2140 instead.
=> Fix for AMD named register race conditions.

.github/workflows/size-impact.yml, .github/workflows/size-impact/generate-size-snapshot.js, .github/workflows/size-impact/report-size-impact.js, package.json
Hello this is a follow up of https://github.com/systemjs/systemjs/issues/2153.
This pull requests adds a GitHub workflow. This workflow is runned every time a pull request is opened or updated. It computes a pull request impact on `dist/*` file sizes and comment the pull request. The workflow uses https://github.com/jsenv/jsenv-github-pull-request-filesize-impact under the hood.
Unfortunately a pull request opened from a fork is not allowed to post comment on the main repository pull request. The workflow is [disabled](https://github.com/systemjs/systemjs/blob/0413e6bf8722881fbeb14ce8a50972b62a78727c/.github/workflows/size-impact.yml#L7) for forks until GitHub finds a solution to [the issue](https://github.community/t5/GitHub-Actions/Token-permissions-for-forks-once-again/td-p/33839). 
I …
=> Add file size impact workflow for pull requests.

.travis.yml
In order for travis ci to be enabled, permissions must be granted. I think that that can be done at https://github.com/organizations/systemjs/settings/oauth_application_policy. I don't have permissions for it. Once that is done, the builds should be publicly visible at https://travis-ci.com/systemjs/systemjs
This uses a headless firefox to run the tests.
=> Running tests and build automatically in CI.

README.md, package.json, src/features/import-map.js, src/system-node.js, test/server.cjs, test/system-node.js
- The link to travis in the readme was pointing to travis-ci.org instead of travis-ci.com
- NodeJS build and tests had some bugs
- `opn` was deprecated and renamed to `open`. See https://www.npmjs.com/package/opn
- I think `open` was not working in the CI environment, likely due to no default browser being set. I'm trying out forcibly opening firefox in CI environments.
- Making `npm run footprint` slightly faster, with concurrently package
- Setting env vars for `npm test` with cross-env, so that it works in windows
=>  Fixing NodeJS build and tests. 

.github/workflows/size-impact.yml, .github/workflows/size-impact/generate-size-snapshot.js, .github/workflows/size-impact/report-size-impact.js, package.json
Hey I made an update to the package commenting pull request with its impact on filesizes. You can now track gzip and brotli sizes 🎉 . 
Just like the previous one I did a basic change
And you can see the corresponding comment generated.
And the comment expanded screenshot.
As you can see, I took the liberty to configure two groups called `core` and `extras`. It's configured in [.github/workflows/size-impact/generate-size-snapshot.js](https://github.com/dmail-fork/systemjs/blob/aa54e413181d1ade9fb8e130120f2c39190ba007/.github/workflows/size-impact/generate-size-snapshot.js#L13).
I thought it would make sense to have them splitted for systemjs.
And of course the gzip and brotli size once expanded.
Good for you ?
=> Upgrade pull request size impact to 3.0.

package.json, src/extras/global.js, test/browser/core.js, test/browser/transform.js, test/browser/worker.js, test/system-node.js, test/test.html
- construct-style-sheets-polyfill requires Symbol polyfill, so I added that to the tests.
- `window` is undefined inside of Web Workers in IE11, so I did a check for that
- `obj instanceof CSSStyleSheet` doesn't work in IE11. Not sure why - likely due to the polyfill
- Fix standard tests verification that assumed web assembly test had executed
- Add promise polyfill to web worker in IE11 tests
- Fix issue where path.sep was being used instead of `/` in a file url.
- Only load the construct-style-sheets-polyfill in tests when needed
I verified that all tests pass in Windows and IE11 now. Am checking Safari and Edge now, too. I have been running the tests against both system.js and system.min.js to test the new terser config, and everything appears to be working
=> Fixing tests in IE11

docs/errors.md, src/extras/transform.js, src/features/import-map.js
There is an error message that occurs both as an error and a warning (unable to resolve specifier). We consolidated them down into a single error, but then split them back up when we created a separate Warnings section in the docs. In doing so, I messed up the numbering of some of the errors / warnings. This PR fixes that.
Also, we consolidated error 7 and 9 in the documentation, but not in the source code. So this fixes that, too.
=> Fix error code mixup

src/features/import-map.js, src/system-node.js, test/system-node.js
This fixes two issues related to prepareImport in system-node.cjs:
1. Calling `applyImportMap()` before `prepareImport()` would result in the import map being discarded during prepareImport(). This is due to `IMPORT_MAP_PROMISE` not being set by applyImportMap, which resulted in import-maps.js setting the import map to an empty map. This bug was hidden by the tests because they were all calling prepareImport inside of a beforeEach. See related https://github.com/systemjs/systemjs/blob/e981b02bca26090a7236434fa4b17b7b26aca7dc/src/features/import-map.js#L30-L31.
2. System.resolve() throws an error in nodejs if you have not called prepareImport() or applyImportMap() first. This behavior makes sense in the browser due to the possibility of external import maps, but doesn't make sense in …
=> Fix bug in system-node where prepareImport overwrote import map.

package.json
Without this, you can't use any of the extras in NodeJS.
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/extras/amd.js' is not defined by "exports" in /Users/joeldenning/code/isomorphic-root-config/node_modules/systemjs/package.json
```
I considered remapping so that the dist was not necessary in import paths. But I think that would be a breaking change since some people are already doing `import 'systemjs/dist/system.js'` (at least in webpack bundles) and have the dist in their code.
=> Adding full dist directory to package.json exports.

package.json
We've had two failed builds in Travis so far due to one nodejs test taking longer than 2 seconds. The reason is that it retrieves a module from the network, which is unreliable. Retrying the tests has worked so far, but increasing the timeout threshold should hopefully make this go away.
=> Increasing timeout for test:node script.

src/system-core.js
When importing a file that doesn't have any dependency, it can be useful to adjust the System format to support `null` setter entries rather than needing to provide an empty `function () {}`.
See for example the RollupJS output here where the first setter is empty - http://rollupjs.org/repl/?version=2.10.9&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuY3ViZSh4KSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHNxdWFyZSUyMGZyb20lMjAnLiUyRnNxdWFyZS5qcyclM0IlNUNuJTVDbmV4cG9ydCUyMCU3QmRlZmF1bHQlMjBhcyUyMHNxdWFyZSU3RCUyMGZyb20lMjAnLiUyRnNxdWFyZS5qcyclM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3 …
=> Make setters optional

src/extras/module-types.js, test/browser/core.js, test/fixtures/browser/content-type-none.json, test/fixtures/browser/content-type-xml.json, test/server.cjs
Currently, if the `Content-Type` header is missing from the response, the error that appears in the console is `TypeError: Cannot read property 'match' of null`. I'd like to preempt that error with a more helpful one, reusing the existing [Error #4](https://github.com/systemjs/systemjs/blob/master/docs/errors.md#4).
=> Add error message for missing content-type header

test/browser/amd.js, test/browser/named-exports.js, test/browser/named-register.js, test/browser/transform.js, test/server.cjs, test/test.html
In mocha@7.2.0 the mocha instance is disposed of automatically after the first call of mocha.run and then only the first imported test suite is actually run. This also won't immediately be marked a failure by travis.ci since the exception is never caught and the browser request timeout exits with a 0 code. https://github.com/systemjs/systemjs/blob/435a797920f3e31947845089bafca73cda0e0950/test/server.cjs#L30-L33
The error message given by the browser is:
```
Uncaught (in promise) Error: Mocha instance is already disposed, cannot start a new test run. Please create a new mocha instance. Be sure to set disable `cleanReferencesAfterRun` when you want to reuse the same mocha instance for multiple test runs.
at createMochaInstanceAlreadyDisposedError (mocha.js:861)
at …
```
=> Fixing browser tests on mocha 7.2.0

docs/hooks.md, src/system-core.js, test/system-core.js
Currently tracking hook onload will be called multiple times when one of dep execution failed, this request aims to align the error handle as instantiate
=> Fix onload

README.md, src/extras/dynamic-import-maps.js, src/features/browser-scripts.js, test/browser/dynamic-import-maps.js, test/fixtures/browser/dynamic-importmap1.json, test/fixtures/browser/dynamic-importmap2.json, test/test.html
This is a follow-on to https://github.com/systemjs/systemjs/pull/2215, with support for dynamic maps rebased to the latest master.
@stevenvachon I've removed the attribute changes triggering updates because that is not a feature that import maps would ever be able to specifying in browsers themselves. Dynamic injections are processed on the moment they are inserted into the DOM, just like script tags.
=> Dynamic maps

src/common.js, src/features/import-maps.js, src/s.js, src/system-core.js, src/system.js, test/browser/core.js, test/fixtures/browser/depcache.js, test/fixtures/browser/depcache1.js, test/fixtures/browser/depcache10.js, test/fixtures/browser/depcache2.js, test/fixtures/browser/depcache3.js, test/fixtures/browser/depcache4.js, test/fixtures/browser/depcache5.js, test/fixtures/browser/depcache6.js, test/fixtures/browser/depcache7.js, test/fixtures/browser/depcache8.js, test/fixtures/browser/depcache9.js, test/fixtures/browser/importmap.json
Posting this early for feedback / informative purposes.
I'm in the process of seeing if we can get depcache from previous versions of SystemJS specified for import maps directly here - https://github.com/WICG/import-maps/pull/210.
Will be working off this experimental implementation to test things out further.
=> depcache implementation

src/features/script-load.js
This fixes the issues pointed out in https://github.com/systemjs/systemjs/pull/2223#issuecomment-669289874, where the timeout is triggering after the ready state has changed thus cancelling an in-progress auto import.
It turns out the timeout mechanism is actually unnecessary as the process of simply checking the registration to clear it in the dynamic case is all that is needed.
The other mechanism to clear the auto import registry entirely has been removed as it's mostly a GC optimization for some impractical edge cases, whereas most proper usage would never hit those. So it also removes some bytes.
=> Fixup and simplify auto import cases

package.json
This explicitly defines the `s.js` loader as an export in exports allowing an easier `systemjs/s.js` resolution.
=> Define s.js as an export

src/features/import-maps.js
This fixes a usage of const as reported in https://github.com/systemjs/systemjs/issues/2227 which crept in with the depcache implementation.
=> Fixup use of const

src/common.js, src/features/import-maps.js, src/features/resolve.js, src/features/script-load.js, src/system-node.js, test/fixtures/browser/importmap.json, test/import-map.js
This implements a new `"integrity"` attribute in the import map, which is consulted when creating scripts for injection to use as the primary integrity mechanism.
In this way a full integrity content security policy can be applied to apps built on top of SystemJS.
Like depcache this is non-standard right now, but I have put together a rough standard outline in the import maps extensions repo at https://github.com/guybedford/import-maps-extensions#integrity.
=> Implement integrity in import map

src/system-core.js, test/browser/core.js, test/fixtures/browser/resolve.js
This implements an `import.meta.resolve` function on the SystemJS context in core allowing contextual resolution for native ES modules converted into the SystemJS format.
This is as landed in ES Module Shims here - https://github.com/guybedford/es-module-shims/pull/89.
By default the implementation is async to support an async resolver function. In future if this is ever made sync that will be an easier hence starting with an async hook makes the most sense. This also matches the implementation under `--experimental-import-meta-resolve` in Node.js.
=> import.meta.resolve implementation

docs/import-maps.md, docs/system-register.md
This updates the documentation to properly cover some of the latest features.
I've also removed the complex composition details from the docs as I don't think that will ever land in any spec now, as a first step to deprecating that chaining behaviour.
I haven't included any of this new stuff in the README yet, but that can always be added later too.
=> Document latest features

README.md
Spent a long time diagnosing this one with a client, so I figured this would be good to add to the documentation to help others avoid the issue.
=> Add IE11 note to external import map documentation.

src/features/depcache.js, src/features/import-maps.js, src/s.js, src/system.js
When auto imports were added, the implementation ended up conflicting with depcache by changing the execution order.
This separates out the depcache code so it hooks instantiate after the script loader properly.
=> Fixup depcache

src/features/script-load.js
This fixes the issue posted at https://github.com/systemjs/systemjs/issues/2243#issuecomment-688385205 that the code to ignore new dynamic imports when checking the auto import list during the loading phase was happening too late - after the new dynamic import with the auto import cache had already been checked.
This brings back the timeout method previously removed in https://github.com/systemjs/systemjs/pull/2225 with a slightly simpler approach.
It appears the script list is not a valid replacement for currentScript because of dynamic injection cases like this. In particular we inject the script into the head, so that document writes in the body will always be later resulting in dynamic imports being incorrectly assigned over the auto imports of body scripts that are currently at the …
=> Fix auto import dynamic imports during loading

README.md, docs/hooks.md, src/extras/transform.js, src/extras/use-default.js
This deprecates the transform extra and also includes a note in both the transform and use default extras that they are deprecated for the next major.
=> Deprecate transform and use default extras

README.md, src/extras/amd.js, src/extras/global.js, src/extras/named-exports.js, src/system-core.js, test/browser/named-exports.js
Now that Node.js has effectively standardized on the shell model like the named exports extra in SystemJS for CommonJS representations, we can follow the same by default in SystemJS.
This inlines the named exports logic into the SystemJS AMD and global extras, and deprecates the separate extra.
=> Inline named exports extra into core

src/features/import-maps.js
This pull request is a proposal to fix https://github.com/systemjs/systemjs/issues/2271.
It dispatches an `error` event on script tags that are failing to load due to a network error.
It replicates the browser behaviour that consists into dispatching an `error` on script tag that are failing to load. 
With this change it becomes possible to detect a script load error by doing:
```html
<script id="main-script" type="systemjs-module" src="./main.js" />
<script type="text/javascript" async>
const mainScript = document.querySelector('#main-script')
mainScript.onerror = () => {
alert('main script load error')
}
</script>
```
This pull requests uses `dispatchEvent`. I have checked the browser compatibility of these two apis to ensure it works for IE11. 
Screenshots taken from
- …
=> Dispatch script loading error

src/features/fetch-load.js
This fixes up the source maps support when using the fetch loader.
=> Add sourcemap normalization to fetch loader

README.md
I think this pattern as a direct polyfill path seems sensible going forward.
The primary benefit is being able to match script attribute behaviours with modules, eg for things like integrity and cross origin options.
=> Redocument systemjs-module

src/features/fetch-load.js
This updates the previous fetch source mapping changes to ensure that the `sourceURL` is only added if it is not already there.
Eg in the Babel loader, we suffix sources with `!system` to distinguish from the original source.
This also removes the Firefox workaround that was added per https://github.com/guybedford/es-module-shims/pull/37 as it seems like this may have been fixed.
=> Only add sourceURL if not present and remove Firefox workaround

docs/api.md, src/extras/global.js, test/browser/core.js, test/fixtures/browser/multiple-globals.js
This adds a backwards-compatible option for altering the global loading extra to use the first created global variable from a module, instead of the last one. 
To use it:
```js
Object.getPrototypeOf(System).firstGlobalProp = true;
```
I've confirmed that loading the official Vue 3 vue.global.js file works with this enabled. Am happy to add tests if this is an acceptable direction to take the global loading extra.
=> Breaking: change global loading to load first created global. Resolves #2272.

src/extras/global.js
This ensures that `firstGlobalProp` works on the prototype or instance.
=> Support firstGlobalProp on instance

README.md
I discovered that webpack 5 no longer rewrites `System.import()` by default.
=> Note about webpack 5

README.md
SystemJS has 85MM downloads per month on jsdelivr. I think the single-spa ecosystem contributes to that some because our CLI sets people up to download from CDN, but also there are probably many others using systemjs on jsdelivr
=> Add jsdelivr badge

src/system-core.js
The current onload hooks actually alter the promise behaviours in swallowing errors. This corrects those cases.
=> Ensure onload hooks retain catches

src/system-core.js, test/browser/core.js, test/fixtures/browser/link-error-child.js, test/fixtures/browser/link-error.js
See #2286. Note that this bug only occurs if the link failure occurs in a dependency, instead of directly on the top level load.
=> Fix deleting modules after link failure. Resolves #2286.

package.json, src/system-core.js
Improves the last PR to only add the unhandled rejection handler in the Node.js build.
=> Footprint improvement for browser

src/features/registry.js, src/system-core.js, test/browser/core.js, test/fixtures/browser/link-error-child2.js, test/fixtures/browser/link-error.js
See https://github.com/systemjs/systemjs/issues/2286#issuecomment-746240996. This test confirms that there is currently a bug. I hope to push a fix in a subsequent commit.
=> Allow deletion of uninstantiated modules whose top level parent import finished. Resolves #2286.

README.md
Hello, I noticed that the closing script tag was missing from the external importmap example.
Cheers
=> Fixed importmap snippet in Readme

docs/import-maps.md, src/features/import-maps.js, test/test.html
Hi,
These changes are for being able to execute custom error handling logic when fetching external import maps. On event of this [error](https://github.com/systemjs/systemjs/blob/master/docs/errors.md#w4), if defined, the script in the `onerror` attribute will be executed.
```html
<script type="systemjs-importmap" onerror="handleError()" src="unable-to-reach/importmap.json"></script>
```
This is addressing this [issue](https://github.com/systemjs/systemjs/issues/2312).
=> Onerror Callback Support for Errors Fetching External Import Map 

src/extras/module-types.js
Hello, thanks for SystemJS, it helped me a lot. However, while using CSS Modules, I found a problem with the relative path of CSS url() in CSSStyleSheet(). The CSS specification states that the partial URLs are interpreted relative to the source of the style sheet, not relative to the document. But the Constructable Stylesheet Objects draft states that the partial URLs are interpreted relative to the document. Thus causing the resource to fail to load. I tried to solve this problem by replacing all the relative paths with absolute one, which might help others. 
[https://www.w3.org/TR/CSS1/#url](https://www.w3.org/TR/CSS1/#url)
[https://wicg.github.io/construct-stylesheets/#dom-cssstylesheet-cssstylesheet](https://wicg.github.io/construct-stylesheets/#dom-cssstylesheet-cssstylesheet)
=> Fix the relative path problem of CSS url() in CSSStyleSheet()

src/extras/named-register.js
See https://github.com/systemjs/systemjs/issues/2327#issuecomment-831756226 and #2293. cc @anhallbe who found the problem.
System core expects to never be called with the string name as the first argument, but named-register does so. The reason the tests pass and named-register works for some people is that named-register overrides `getRegister` to retrieve from `registerRegistry` for named registers. However, when that doesn't happen, the `lastRegister` in system core is just incorrect!
=> Fix named-register.js - omit name from register call. Resolves #2293.

package.json
I'd love if I could use the traditional
```bash
nodejs -p "require.resolve('systemjs/package.json')"
```
to find the module root directory.
with current master:
```text
throw e;
^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /tmp/sandbox/node_modules/systemjs/package.json imported from …
```
with my branch:
```text
/tmp/sandbox/node_modules/systemjs/package.json
```
=> Export package.json so tools can more easily access meta data

docs/errors.md, src/extras/amd.js, test/browser/amd.js
See #2331. My comment there explains how the current behavior of amd.js' `System.getRegister()` implementation can be problematic.
This PR refactors the entire amd.js extra to be a lot simpler - `window.define()` calls `System.register()`, instead of maintaining its own latest amd register in memory. This way, system-core is in charge of clearing out the lastRegister and it also avoids much of the tricky edge cases with `tmpRegister`, `System.getRegister()`, and named registers.
All of the tests still pass, which I was quite excited about! I was thinking there would be edge cases where the getRegister functionality would expose nuances, but those were not revealed by any existing tests. I think there's a decent chance that such edge cases exist, but are not yet covered with tests. …
=> Refactor amd.js to only call System.register. Resolves #2331.

src/extras/amd.js, src/extras/named-exports.js, src/system-core.js, test/browser/amd.js, test/fixtures/browser/amd-null-module.js
See #2332 - both system-core and named-exports do not work if `_export(null)` occurs, as it appears to be invalid. However, amd.js would do this as explained in #2332. My fix here is specific only to null, rather than an object check + null check, since it's valid to loop over the keys of functions for re-exporting.
=> Do not export null as module.exports in amd.js. Resolves #2332.

package.json
This would fix this warning:
```
DeprecationWarning: Use of deprecated folder mapping "./dist/" in the "exports" field module resolution of the package at /path/to/node_modules/systemjs/package.json.
Update this package.json to use a subpath pattern like "./dist/*".
```
=> Fix warning with node 16

docs/hooks.md, src/extras/named-register.js, src/extras/transform.js, src/features/fetch-load.js, src/features/script-load.js, src/features/worker-load.js, test/browser/named-register.js, test/fixtures/browser/named-instantiate-count.js, test/fixtures/browser/named-self-import.js
This resolves #2349. It fixes two bugs:
1. When loading a bundle via System.import() with named registers, it is no longer possible for the first named register in the bundle to instantiate twice. Previously this was true, as the register array was instantiated once for the bundle of the module and once for the name it gave itself via a named register.
2. The named-register extra now always returns the first named register, rather than sometimes the first named define and sometimes the last named register
Demonstration of the bugs:
1. (todo)
2. [Last named register returned (script-load.js)](https://codesandbox.io/s/objective-moon-sdpp8?file=/index.html) and [First named register returned (transform.js)](https://codesandbox.io/s/hopeful-snyder-q9nq8?file=/index.html)
The changes I had to …
=> Fixes for named-register extra.

src/extras/named-register.js
See #2359. During my refactor of named register in https://github.com/systemjs/systemjs/pull/2352, I unintentionally switched from setTimeout to Promise.resolve. This reverts that unintentional change and seems to fix the problem in the codesandbox in #2359
=> Use Promise.resolve in named-register. Resolves #2359.

.travis.yml, docs/hooks.md, src/extras/module-types.js, src/features/import-maps.js, test/browser/core.js
=> Call fetch hook when retrieving external import maps. Resolves #2374.

.github/workflows/size-impact.yml
Fixes up the Node.js version to work with the current build scripts.
=> ci: fix size impact script Node.js version

src/system-core.js, test/fixtures/tla/concurrent-top-level-import-threads/async-dep.js, test/fixtures/tla/concurrent-top-level-import-threads/dep.js, test/fixtures/tla/concurrent-top-level-import-threads/main.js, test/system-core.mjs
Let me illustrate this BUG.
Here's 3 modules:
```ts
// main
export { stamp } from './dep.js';
// dep
import './async-dep.js';
export const stamp = Date.now();
// async-dep
await Promise.resolve();
```
And the top level execution flow:
```ts
const thread1 = import('main'); // #1
const thread2 = import('dep'); // #2
await thread1; // #3
await thread2; // #4
```
For module `dep`:
At the end of line #1, `load.E` was created. But `load.e` kept non-nil, since `dep` has async dependencies - the `load.e` only reset when `load.E` resolved.
Now enter line #2, because `!!load.e`, another `load.E`  would be created.
Starting from line #3, the two `load.E` raced - both call and reset `load.e`.
=> Fix a concurrent bug due to async execution

src/err-msg.js, src/features/import-maps.js
All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Replace `git.io` within the error message with its original URL.
=> refactor: replace all `git.io` within the error message

docs/api.md, docs/import-maps.md, src/features/import-maps.js, src/system-node.js, test/browser/dynamic-import-maps.js, test/system-node.mjs
=> expose addImportMap

src/system-core.js
import assert will going to make into stage 4, add a placeholder for future impl, this may help the module-types extra (will add to core), a placeholder mean the bundler can pass the assertion, but currently only for dynamic import.
for  `import 'xyz' assert {type:'xyz'}`, this maybe harder to decided the how api look.
=> add dynamic import meta placeholder

README.md
BeyondJS uses SystemJS to resolve imports in web projects and microfrontends built with web components.
=> feat: Add BeyondJS as Project that uses SystemJS

src/extras/module-types.js, test/browser/core.js, test/fixtures/css-modules/url-without-quotes.css
This PR addresses the issue of undefined being concatenated into url strings when urls aren't wrapped in quotes.
I believe the fixture css I've added is valid for urls. I've not used chomp before. It changed some dist files when I ran it locally but I'm guessing you wouldn't want me to commit these changes in the PR. 🤔 
fixes: #2460
=> Fix: Module types should support urls without quotes

src/features/import-maps.js
Fixes #2478 
Invoke like:
`<script type="system-js-importmap" src="https://import_map_url" fetchpriority="high">`
=> Support fetch priority with import maps

src/features/import-maps.js, test/system-core.mjs
During the implementation of the library, I needed to read the values from the mapping without the need to call the import file again via fetch. Since I didn't see anything within the code that could provide these values, I'm sending this addition if possible.
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf8" />
<link rel="icon" href="data:," />
<script type="systemjs-importmap" src="./import-map.json"></script>
</head>
<body>
<script>
const importMap = System.getImportMap();
</script>
</body>
</html>
```
=> feat: add support for reading the mapping of loaded imports

src/extras/amd.js, test/browser/amd.js, test/fixtures/browser/amd-module-meta.js
AMD modules loaded via SystemJS should have some way of knowing where they are loading from so they can load their assets. This is mentioned in the requirejs docs [here](https://github.com/requirejs/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#module). With this an amd webpack build can then use it to setup `__webpack_public_path__`. e.g.
```
__webpack_public_path__ = module.uri.slice(0, module.uri.lastIndexOf('/') + 1);
```
Fixes: #2386
**Notes for reviewers:**
Should I update version and run the `build` script in this PR to update the dist files or does that happen via github-actions after a merge to main?
=> Feat: Support module.uri in AMD extra
